import { db } from '@/db';
import { notes } from '@/db/schema';

async function main() {
    const sampleNotes = [
        // Notes for demo-user-1 (5 notes)
        {
            title: 'Q2 Sprint Planning Meeting',
            content: '## Q2 Sprint Goals\n\n### Key Objectives\n- Launch new dashboard redesign\n- Implement user feedback system\n- Improve API performance by 30%\n\n### Team Assignments\n- Frontend: Sarah & Mike\n- Backend: Alex\n- DevOps: Jordan\n\n### Timeline\n- Sprint 1: April 1-14\n- Sprint 2: April 15-28\n- Sprint 3: May 1-15',
            userId: 'demo-user-1',
            categoryId: 1,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (3 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (3 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Client Presentation Outline',
            content: '## Presentation Flow\n\n1. **Introduction** (5 mins)\n   - Company overview\n   - Team introductions\n\n2. **Problem Statement** (10 mins)\n   - Current challenges\n   - Market analysis\n\n3. **Our Solution** (15 mins)\n   - Product demo\n   - Key features\n   - Competitive advantages\n\n4. **Implementation Plan** (10 mins)\n   - Timeline\n   - Milestones\n   - Resource allocation\n\n5. **Q&A** (10 mins)',
            userId: 'demo-user-1',
            categoryId: 1,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (5 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (5 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Weekend Trip Planning',
            content: '## Mountain Getaway - June 15-17\n\n### Accommodation\n- Booked: Pine Lodge Resort\n- Check-in: Friday 3 PM\n- Check-out: Sunday 11 AM\n\n### Activities\n- Hiking trail: Eagle Peak (Saturday morning)\n- Kayaking: Lake Vista (Saturday afternoon)\n- Local winery tour (Sunday morning)\n\n### Packing List\n- [ ] Hiking boots\n- [ ] Camera\n- [ ] Sunscreen\n- [ ] Water bottles\n- [ ] Light jacket',
            userId: 'demo-user-1',
            categoryId: 2,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (7 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (7 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'App Feature Ideas - AI Integration',
            content: '## AI-Powered Features\n\n### Auto-Summarization\n- Automatically summarize long notes\n- Extract key points\n- Generate table of contents\n\n### Smart Tags\n- Auto-suggest tags based on content\n- Machine learning tag recommendations\n\n### Voice-to-Text\n- Real-time transcription\n- Multi-language support\n- Speaker identification\n\n### Smart Search\n- Semantic search across all notes\n- Natural language queries\n- Context-aware results',
            userId: 'demo-user-1',
            categoryId: 3,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (10 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (2 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Archived Project: Mobile App v1',
            content: '## Mobile App v1 - Completed\n\n### Project Overview\nFirst version of mobile app launched in March 2024.\n\n### Key Features Delivered\n- User authentication\n- Note creation and editing\n- Offline sync\n- Push notifications\n\n### Lessons Learned\n- React Native performance excellent\n- Need better error handling\n- User onboarding needs improvement\n\n### Metrics\n- 5,000+ downloads in first month\n- 4.2 star rating\n- 85% retention rate',
            userId: 'demo-user-1',
            categoryId: 1,
            isFavorite: false,
            isArchived: true,
            isDeleted: false,
            createdAt: new Date(Date.now() - (30 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (30 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        // Notes for demo-user-2 (6 notes)
        {
            title: 'E-Commerce Platform Redesign',
            content: '## Project: E-Commerce Redesign\n\n### Current Issues\n- Checkout process too complex (5 steps)\n- Mobile experience poor\n- Page load times > 3 seconds\n\n### Proposed Solutions\n- Simplified 2-step checkout\n- Mobile-first design\n- Image optimization\n- Lazy loading implementation\n\n### Success Metrics\n- Reduce cart abandonment by 20%\n- Improve mobile conversion by 30%\n- Decrease load time to < 1.5 seconds\n\n### Budget: $45,000\n### Timeline: 12 weeks',
            userId: 'demo-user-2',
            categoryId: 4,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (2 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (1 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Marketing Campaign Ideas',
            content: '## Q3 Marketing Campaign\n\n### Campaign Theme: "Simplify Your Workflow"\n\n### Channels\n1. **Social Media**\n   - LinkedIn: B2B focus\n   - Twitter: Tech community engagement\n   - Instagram: Visual storytelling\n\n2. **Content Marketing**\n   - Blog posts (2 per week)\n   - Video tutorials\n   - Case studies\n\n3. **Paid Advertising**\n   - Google Ads: $5K/month\n   - LinkedIn Ads: $3K/month\n\n### KPIs\n- Website traffic: +40%\n- Lead generation: 200 new leads\n- Trial signups: +50%',
            userId: 'demo-user-2',
            categoryId: 4,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (4 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (4 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'TypeScript Advanced Patterns',
            content: '## TypeScript Learning Notes\n\n### Utility Types\n\n**Partial<T>** - Makes all properties optional\n\ntype User = { name: string; email: string };\ntype PartialUser = Partial<User>;\n// { name?: string; email?: string }\n\n\n**Pick<T, K>** - Select specific properties\n\ntype UserPreview = Pick<User, \'name\'>;\n// { name: string }\n\n\n### Generic Constraints\n\ninterface Lengthwise {\n  length: number;\n}\n\nfunction logLength<T extends Lengthwise>(arg: T): T {\n  console.log(arg.length);\n  return arg;\n}\n\n\n### Mapped Types\n\ntype Readonly<T> = {\n  readonly [P in keyof T]: T[P];\n};\n',
            userId: 'demo-user-2',
            categoryId: 5,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (6 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (6 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Docker & Kubernetes Notes',
            content: '## Container Orchestration\n\n### Docker Basics\n\n**Dockerfile Example**\ndockerfile\nFROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]\n\n\n**Common Commands**\nbash\ndocker build -t myapp .\ndocker run -p 3000:3000 myapp\ndocker-compose up -d\n\n\n### Kubernetes Concepts\n\n- **Pods**: Smallest deployable units\n- **Services**: Network access to pods\n- **Deployments**: Manage pod replicas\n- **ConfigMaps**: Configuration data\n- **Secrets**: Sensitive data\n\n### kubectl Commands\nbash\nkubectl get pods\nkubectl apply -f deployment.yaml\nkubectl logs <pod-name>\nkubectl scale deployment myapp --replicas=3\n',
            userId: 'demo-user-2',
            categoryId: 5,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (8 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (8 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Database Design Best Practices',
            content: '## Database Design Principles\n\n### Normalization\n\n**1NF (First Normal Form)**\n- Eliminate repeating groups\n- Each cell contains atomic values\n\n**2NF (Second Normal Form)**\n- Meet 1NF requirements\n- Remove partial dependencies\n\n**3NF (Third Normal Form)**\n- Meet 2NF requirements\n- Remove transitive dependencies\n\n### Indexing Strategies\n\nsql\n-- Single column index\nCREATE INDEX idx_email ON users(email);\n\n-- Composite index\nCREATE INDEX idx_user_date ON orders(user_id, created_at);\n\n-- Unique index\nCREATE UNIQUE INDEX idx_username ON users(username);\n\n\n### Performance Tips\n- Use appropriate data types\n- Index foreign keys\n- Avoid SELECT *\n- Use EXPLAIN for query analysis\n- Partition large tables',
            userId: 'demo-user-2',
            categoryId: 5,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (12 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (12 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Budget Proposal - Team Expansion',
            content: '## Q4 Budget Request: Team Growth\n\n### Proposed New Hires\n\n1. **Senior Backend Developer**\n   - Salary: $120K/year\n   - Start date: October 1\n   - Focus: API architecture, microservices\n\n2. **UX Designer**\n   - Salary: $95K/year\n   - Start date: November 1\n   - Focus: Product design, user research\n\n3. **DevOps Engineer**\n   - Salary: $110K/year\n   - Start date: October 15\n   - Focus: CI/CD, cloud infrastructure\n\n### Additional Costs\n- Recruitment fees: $30K\n- Equipment & software: $15K\n- Training & onboarding: $10K\n\n### Total Investment: $380K\n### Expected ROI: 25% productivity increase',
            userId: 'demo-user-2',
            categoryId: 4,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (15 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (15 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        // Notes for demo-user-3 (5 notes)
        {
            title: 'React Custom Hooks Library',
            content: '## Useful React Hooks\n\n### useDebounce Hook\n\nimport { useState, useEffect } from \'react\';\n\nfunction useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState<T>(value);\n\n  useEffect(() => {\n    const handler = setTimeout(() => {\n      setDebouncedValue(value);\n    }, delay);\n\n    return () => clearTimeout(handler);\n  }, [value, delay]);\n\n  return debouncedValue;\n}\n\n// Usage\nconst searchTerm = useDebounce(inputValue, 500);\n\n\n### useLocalStorage Hook\n\nfunction useLocalStorage<T>(key: string, initialValue: T) {\n  const [storedValue, setStoredValue] = useState<T>(() => {\n    try {\n      const item = window.localStorage.getItem(key);\n      return item ? JSON.parse(item) : initialValue;\n    } catch (error) {\n      return initialValue;\n    }\n  });\n\n  const setValue = (value: T | ((val: T) => T)) => {\n    const valueToStore = value instanceof Function ? value(storedValue) : value;\n    setStoredValue(valueToStore);\n    window.localStorage.setItem(key, JSON.stringify(valueToStore));\n  };\n\n  return [storedValue, setValue] as const;\n}\n',
            userId: 'demo-user-3',
            categoryId: 6,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (1 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (1 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Python API Client Template',
            content: '## REST API Client Template\n\npython\nimport requests\nfrom typing import Dict, Any, Optional\nimport logging\n\nlogger = logging.getLogger(__name__)\n\nclass APIClient:\n    def __init__(self, base_url: str, api_key: str):\n        self.base_url = base_url\n        self.session = requests.Session()\n        self.session.headers.update({\n            \'Authorization\': f\'Bearer {api_key}\',\n            \'Content-Type\': \'application/json\'\n        })\n\n    def _request(self, method: str, endpoint: str, **kwargs) -> Dict[Any, Any]:\n        url = f\'{self.base_url}{endpoint}\'\n        try:\n            response = self.session.request(method, url, **kwargs)\n            response.raise_for_status()\n            return response.json()\n        except requests.exceptions.RequestException as e:\n            logger.error(f\'API request failed: {e}\')\n            raise\n\n    def get(self, endpoint: str, params: Optional[Dict] = None) -> Dict:\n        return self._request(\'GET\', endpoint, params=params)\n\n    def post(self, endpoint: str, data: Dict) -> Dict:\n        return self._request(\'POST\', endpoint, json=data)\n\n    def put(self, endpoint: str, data: Dict) -> Dict:\n        return self._request(\'PUT\', endpoint, json=data)\n\n    def delete(self, endpoint: str) -> Dict:\n        return self._request(\'DELETE\', endpoint)\n\n# Usage\nclient = APIClient(\'https://api.example.com\', \'your-api-key\')\nusers = client.get(\'/users\', params={\'limit\': 10})\n',
            userId: 'demo-user-3',
            categoryId: 6,
            isFavorite: true,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (3 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (3 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Next.js API Route Patterns',
            content: '## Next.js API Best Practices\n\n### Basic API Route\n\nimport { NextRequest, NextResponse } from \'next/server\';\n\nexport async function GET(request: NextRequest) {\n  const { searchParams } = new URL(request.url);\n  const id = searchParams.get(\'id\');\n\n  try {\n    const data = await fetchData(id);\n    return NextResponse.json(data);\n  } catch (error) {\n    return NextResponse.json(\n      { error: \'Internal server error\' },\n      { status: 500 }\n    );\n  }\n}\n\n\n### Middleware for Auth\n\nimport { NextResponse } from \'next/server\';\nimport type { NextRequest } from \'next/server\';\n\nexport function middleware(request: NextRequest) {\n  const token = request.cookies.get(\'auth-token\');\n  \n  if (!token) {\n    return NextResponse.redirect(new URL(\'/login\', request.url));\n  }\n  \n  return NextResponse.next();\n}\n\nexport const config = {\n  matcher: \'/api/protected/:path*\',\n};\n\n\n### Rate Limiting\n\nconst rateLimit = new Map<string, number[]>();\n\nfunction checkRateLimit(ip: string): boolean {\n  const now = Date.now();\n  const windowMs = 60000; // 1 minute\n  const maxRequests = 10;\n  \n  const requests = rateLimit.get(ip) || [];\n  const recentRequests = requests.filter(time => now - time < windowMs);\n  \n  if (recentRequests.length >= maxRequests) {\n    return false;\n  }\n  \n  recentRequests.push(now);\n  rateLimit.set(ip, recentRequests);\n  return true;\n}\n',
            userId: 'demo-user-3',
            categoryId: 6,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (5 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (5 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'API Documentation Guidelines',
            content: '## API Documentation Template\n\n### Endpoint Overview\n\n**Base URL:** `https://api.example.com/v1`\n\n**Authentication:** Bearer token in Authorization header\n\n### Endpoints\n\n#### GET /users\n\nRetrieve a list of users.\n\n**Query Parameters:**\n- `limit` (integer, optional): Number of results (default: 10, max: 100)\n- `offset` (integer, optional): Pagination offset (default: 0)\n- `search` (string, optional): Search by name or email\n\n**Response:**\non\n{\n  "users": [\n    {\n      "id": 1,\n      "name": "John Doe",\n      "email": "john@example.com",\n      "createdAt": "2024-01-15T10:30:00Z"\n    }\n  ],\n  "total": 100,\n  "limit": 10,\n  "offset": 0\n}\n\n\n**Status Codes:**\n- `200 OK`: Success\n- `400 Bad Request`: Invalid parameters\n- `401 Unauthorized`: Missing or invalid token\n- `500 Internal Server Error`: Server error\n\n#### POST /users\n\nCreate a new user.\n\n**Request Body:**\non\n{\n  "name": "John Doe",\n  "email": "john@example.com",\n  "password": "secure123"\n}\n\n\n**Response:**\non\n{\n  "id": 1,\n  "name": "John Doe",\n  "email": "john@example.com",\n  "createdAt": "2024-01-15T10:30:00Z"\n}\n\n\n**Status Codes:**\n- `201 Created`: User created successfully\n- `400 Bad Request`: Validation error\n- `409 Conflict`: Email already exists',
            userId: 'demo-user-3',
            categoryId: 7,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (9 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (9 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            title: 'Git Workflow Documentation',
            content: '## Git Best Practices\n\n### Branch Naming Convention\n\n- **Feature branches:** `feature/user-authentication`\n- **Bug fixes:** `bugfix/login-error`\n- **Hotfixes:** `hotfix/critical-security-patch`\n- **Release branches:** `release/v1.2.0`\n\n### Commit Message Format\n\n\n<type>(<scope>): <subject>\n\n<body>\n\n<footer>\n\n\n**Types:**\n- `feat`: New feature\n- `fix`: Bug fix\n- `docs`: Documentation changes\n- `style`: Code style changes (formatting)\n- `refactor`: Code refactoring\n- `test`: Adding tests\n- `chore`: Build process or auxiliary tool changes\n\n**Examples:**\n\nfeat(auth): add OAuth2 authentication\n\nImplemented Google and GitHub OAuth providers\nAdded user session management\n\nCloses #123\n\n\n### Pull Request Template\n\nmarkdown\n## Description\nBrief description of changes\n\n## Type of Change\n- [ ] Bug fix\n- [ ] New feature\n- [ ] Breaking change\n- [ ] Documentation update\n\n## Testing\n- [ ] Unit tests added/updated\n- [ ] Integration tests pass\n- [ ] Manual testing completed\n\n## Screenshots\n(if applicable)\n\n## Related Issues\nCloses #XXX\n\n\n### Useful Commands\n\nbash\n# Interactive rebase last 3 commits\ngit rebase -i HEAD~3\n\n# Stash with message\ngit stash save "work in progress on feature X"\n\n# Cherry-pick specific commit\ngit cherry-pick <commit-hash>\n\n# Reset to remote branch\ngit reset --hard origin/main\n\n# Show changes in last commit\ngit show HEAD\n',
            userId: 'demo-user-3',
            categoryId: 7,
            isFavorite: false,
            isArchived: false,
            isDeleted: false,
            createdAt: new Date(Date.now() - (14 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(Date.now() - (14 * 24 * 60 * 60 * 1000)).toISOString(),
        },
    ];

    await db.insert(notes).values(sampleNotes);

    console.log('✅ Notes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});